Train:
  batch_size: 1 # 5 for kitti and 100 for cifar works
  learning_rate: 0.0001
  reg: 0
  epochs: 5
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  gamma: 1
  model_type: "simpleYOLO" # linear, alexnet, resnet, customcnn, customcnn_kitti, simpleYOLO
  data_type: "kitti" # cifar, kitti
  training_split_percentage: 0.8
  dataset_percentage: .2