Train:
  batch_size: 1 # 5 for kitti and 100 for cifar works
  learning_rate: 0.005
  reg: 0
  epochs: 15
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  gamma: 1
  model_type: "customcnn_kitti" # linear, alexnet, resnet, customcnn, customcnn_kitti
  data_type: "kitti" # cifar, kitti